chore(): update and add config files

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,17 +1,8 @@
-echo 'Check for linting errors...'
-npm run format ||
-(echo 'Linting errors or tests failed. Please fix them before commiting.' && exit 1)
+echo -e "\033[1;34mChecking lint and formatting code...\033[0m"
 
-echo 'Check unit tests...'
-npm run test ||
-(echo 'Your unit tests failed. Please fix them before commiting.' && exit 1)
+npm run format || (
+  echo -e "\033[1;31mSome formatting errors were found, see the log for more information.\033[0m"
+  exit 1
+)
 
-echo 'Check integration tests...'
-npm run test:integration ||
-(echo 'Your integration tests failed. Please fix them before commiting.' && exit 1)
-
-echo 'Check e2e tests...'
-npm run test:e2e ||
-(echo 'Your e2e tests failed. Please fix them before commiting.' && exit 1)
-
-echo 'Done'
+echo -e "\033[1;32mDone\033[0m"
